//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIY_Jewelry_Website {

    public partial class Dashboard {

        /// <summary>
        /// hfEditId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEditId;

        /// <summary>
        /// txtEditFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditFullName;

        /// <summary>
        /// txtEditEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;

        /// <summary>
        /// txtEditUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditUsername;

        /// <summary>
        /// GridViewUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridViewUsers;

        /// <summary>
        /// SqlDataSourceUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceUsers;
    }
}
